name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - "**"
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://20.42.109.216:5432/hbsgooldb
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASS }}
        run: mvn -B test

      - name: Build JAR
        if: github.ref == 'refs/heads/master'
        run: mvn -B clean package -DskipTests

      - name: Save JAR as artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar

  deploy:
    name: Build Image & Deploy
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      # Necesario para tener el Dockerfile
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Rename JAR
        run: mv *.jar app.jar

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hbsgool-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hbsgool-backend:${{ github.sha }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/HBSGool
            sudo docker compose pull backend
            sudo docker compose up -d backend
            sudo docker image prune -f
